### PR TITLE
added hotdrop replacement to django native get_user_model

### PR DESCRIPTION
**Pull request by agriev**
patch adds support for custom user model instead of stock one.

### CODE REVIEW

**Comment by javrasya** [comment]
Hi @agriev ,

Thanks for the PR. I will see why the build is failing and then merge this after it passes.

**Comment by agriev** [comment]
speaking of which - could be good idea to add python 3.9.x tests. django channels related projects almost forced to use it currently

**Comment by javrasya** [comment]
Hi @agriev, I fixed master. Can you rebase your fork from django-river master and let the build re-run?

**Comment by agriev** [comment]
@javrasya done :)

**Review by javrasya — APPROVED** [review]

**Comment by javrasya** [comment]
It has been released as part of 0.7.0 @agriev. Thank you for your contribution 🙏

**Pull request merged**
